### ISSUE TITLE
Bright black is not brighter

### ISSUE THREAD

**Issue by mbark** [challenger-deep-theme/iterm#2]
The bright black color is defined as a dark black color rather than a brighter black.

I'm not sure if this is by design or not -- but it does appear that a lot of my `zsh` plugins rely on bright black being more of a gray color. And when I used dracula it also had color that was brighter than the background color.

For example, `autosuggestions` with the default black:
![default black](https://user-images.githubusercontent.com/1579384/41081961-f4050c9c-6a2c-11e8-8401-c8a18620f600.png)

Whereas I expected it to look something more like this (which is just the black made brighter):
![brighter black](https://user-images.githubusercontent.com/1579384/41081955-f09187d4-6a2c-11e8-97e6-26a6f5c5ab8d.png)

p.s. Thanks for the amazing color scheme! I never thought I'd find a color scheme that would make me switch from dracula, but this is just 👌

**Comment by MaxSt** [comment]
Thank you for reporting this and sorry for answering so late.
This should be fixed with https://github.com/challenger-deep-theme/iterm/commit/41da7880b8add7d2d2ee2c08146305c4c31f719 and should like this now:
![autosuggest](https://user-images.githubusercontent.com/720801/55070575-db80c580-5086-11e9-89ac-42ff390cc9ea.png)
